import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { SessionProvider } from "next-auth/react"
import '@/app/globals.css';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Xuan Viet Dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider
          options={{ key: 'css' }}
        >
          <AntdRegistry>
            <SessionProvider>
              {children}
            </SessionProvider>
          </AntdRegistry>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
